#!/bin/bash 
host=$'Master\n'
ssh azureuser@slave1 exit > /dev/null 2>&1 &&  host+=$'Slave1\n' 
ssh azureuser@slave2 exit > /dev/null 2>&1 &&  host+=$'Slave2\n' 
> myhostfile
echo "$host" > myhostfile
cat myhostfile
gnome-terminal -e "bash -c 'mpiexec -hostfile myhostfile python3 merged2.py'"
#mpiexec -hostfile myhostfile python3 merged2.py
#watch -n 3 ./watch

